# Generated by Django 4.2.7 on 2023-11-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengers',
            fields=[
                ('passengerid', models.BigIntegerField(db_column='PassengerId', primary_key=True, serialize=False)),
                ('survived', models.TextField(blank=True, db_column='Survived', null=True)),
                ('pclass', models.BigIntegerField(blank=True, db_column='Pclass', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('sex', models.TextField(blank=True, db_column='Sex', null=True)),
                ('age', models.FloatField(blank=True, db_column='Age', null=True)),
                ('sibsp', models.BigIntegerField(blank=True, db_column='SibSp', null=True)),
                ('parch', models.TextField(blank=True, db_column='Parch', null=True)),
                ('ticket', models.TextField(blank=True, db_column='Ticket', null=True)),
                ('fare', models.FloatField(blank=True, db_column='Fare', null=True)),
                ('cabin', models.TextField(blank=True, db_column='Cabin', null=True)),
                ('embarked', models.TextField(blank=True, db_column='Embarked', null=True)),
            ],
            options={
                'db_table': 'passengers',
                'managed': False,
            },
        ),
    ]
